name: nova
description: "Nova - Профессиональный конвертер видео с автоматическим расчётом битрейта"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Работа с файлами
  file_picker: ^8.1.4
  path_provider: ^2.1.2
  path: ^1.8.3
  shared_preferences: ^2.2.3
  
  # UI компоненты  
  google_fonts: ^8.0.2
  flutter_animate: ^4.3.0
  percent_indicator: ^4.2.3
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.4
  msix: ^3.16.7
  
  # Утилиты
  desktop_drop: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: false
  ios: false
  image_path: "assets/images/logo-nova-highres.png"
  macos:
    generate: true
    image_path: "assets/images/logo-nova-highres.png"
  windows:
    generate: true
    image_path: "assets/images/logo-nova-highres.png"
  linux:
    generate: true
    image_path: "assets/images/logo-nova-highres.png"

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/images/

msix_config:
  display_name: Nova Video Converter
  publisher_display_name: Nova
  publisher: CN=Nova
  identity_name: nova.videoconverter
  msix_version: 1.0.0.0
  logo_path: assets/images/logo-nova-highres.png
  capabilities: internetClient
  execution_alias: nova
  install_location: localappdata
  install: false
  install_certificate: false
